### ISSUE TITLE
Aggregations produce incorrect results depending on label ordering

### ISSUE THREAD

**Issue by Reprazent** [thanos-community/promql-engine#161]
Playing around with a simple query using the new promql engine we noticed different results for aggregations based on label ordering in the aggregation:

![image](https://user-images.githubusercontent.com/397196/214304732-b403dad6-1299-4a7c-aa20-4daf10ac8aff.png)

The top result is the correct one.

Trying this out for GitLab.com in https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/1996

<details><summary>Build information:</summary>

version | 0.29.0
-- | --
194e1fadf4302341a0c70c28c0e3f3c658616c19
HEAD
root@a0c7bba6c208
20221103-14:28:25
go1.19.3
</details>

**Comment by fpetkovski** [comment]
Hey @Reprazent, thanks for reporting this. I believe we already fixed it in https://github.com/thanos-community/promql-engine/pull/73. 

Are you using the engine in Thanos, and which version are you using?

**Comment by Reprazent** [comment]
@fpetkovski Thanks for your swift reply! We were using the engine in Thanos. [v0.29.0 `194e1fadf4302341a0c70c28c0e3f3c658616c19`](https://github.com/thanos-io/thanos/tree/v0.29.0). Would this be solved by upgrading to 0.30?

**Comment by Reprazent** [comment]
@fpetkovski It looks like it would, the version in v0.30.0 is d68c8139c070, which includes #73.

I'll close this, sorry for the noise!

**Comment by fpetkovski** [comment]
No worries, feel free to reopen this issue if you still notice the same problem.
