### ISSUE TITLE
Query API exposed by Thanos not guaranteed to be the same as Prometheus 2.x. API

### ISSUE THREAD

**Issue by WindIsClear** [thanos-community/promql-engine#194]
Query API exposed by Thanos  of GET /api/v1/label/<label_name>/values  not guaranteed to be the same as Prometheus 2.x. API. When I added the mact[] parameter thanos queried the full amount of data

**Comment by yeya24** [comment]
Please open an issue in https://github.com/thanos-io/thanos instead.
I think for the semantics of the API, Thanos should be the same as Prometheus. There probably have some subtle differences like default time range based on your setting.
