### ISSUE TITLE
Bug: query caused new engine to panic

### ISSUE THREAD

**Issue by yeya24** [thanos-community/promql-engine#201]
```
-floor(histogram_quantile(-time(), tan(group without () ({series="2"} offset 4m14s))))
    engine_test.go:78: engine_test.go:78: ""
        
         unexpected error: unexpected error: runtime error: invalid memory address or nil pointer dereference
```

Similar to https://github.com/thanos-community/promql-engine/issues/200, this instant query could caused the new engine to panic during execution. `Exec` returns `runtime error: invalid memory address or nil pointer dereference` error while the old engine worked without issues on the same query.

**Comment by mhoffm-aiven** [comment]
Should also be fixed by https://github.com/thanos-community/promql-engine/pull/198 I think

**Comment by yeya24** [comment]
Right, seems the same issue.
