### ISSUE TITLE
Bug: Unary scalar function caused histogram_quantile operator panic

### ISSUE THREAD

**Issue by yeya24** [thanos-community/promql-engine#202]
```
histogram_quantile(-time(), sum by (series, __name__) ({pod="nginx-3"}))
```

A query like this caused new engine to panic here https://github.com/thanos-community/promql-engine/blob/main/worker/worker.go#L81. The `ctx` seems becoming nil.

```
unexpected error: unexpected error: runtime error: invalid memory address or nil pointer dereference
```

I have tested it is related to the first scalar function argument. A unary operator with a function that returns scalar makes it panic.

If I do `histogram_quantile(-0.5, sum by (series, __name__) ({pod="nginx-3"}))` or `histogram_quantile(time(), sum by (series, __name__) ({pod="nginx-3"}))` everything works. But if it is `-time()` it panics.

**Comment by mhoffm-aiven** [comment]
Should be fixed by https://github.com/thanos-community/promql-engine/pull/198 I think

**Comment by yeya24** [comment]
Ah right seems duplicate with #201
