### ISSUE TITLE
Refactor PromQL function call implementation

### ISSUE THREAD

**Issue by saswatamcode** [thanos-community/promql-engine#23]
Currently `plan` checks for only the first argument type in `*parser.Call` before deciding on further plan. But we can have functions with multiple different argument types with combinations of instant/range/scalar vectors as outlined [here](https://prometheus.io/docs/prometheus/latest/querying/functions). 

Refactoring it to handle such cases accurately and to also check arg types before executing, will align behavior with old engine. 🙂

**Comment by saswatamcode** [comment]
Working on this!

**Comment by yeya24** [comment]
The refactoring would help with functions that require arguments, right? 
Since I am currently looking into `histogram_quantile` function which requires arguments, just double checking if this issue would cover that usecase.

**Comment by saswatamcode** [comment]
Yup, it would. I was planning on implementing the `clamp.*` ones and noticed.

**Comment by yeya24** [comment]
@saswatamcode Any progress right now? I feel a lot of things for the function call as well as the `matrixSelector` needs to be refactored to support https://github.com/thanos-community/promql-engine/issues/39

**Comment by saswatamcode** [comment]
Yup! It's a bit difficult to get right. I should have something workable by end of this week! 🙂

**Comment by fpetkovski** [comment]
What could help is the fact we can use currying to transform function with arguments into functions without arguments. 

In the case of golang, we can have functions that take the necessary arguments and return a function with the vector as input. Because the returned function is a clojure, it can reference the arguments passed in the outer function.

**Comment by fpetkovski** [comment]
@saswatamcode should we close this? We have a dedicated issue for tracking the last edge case: https://github.com/thanos-community/promql-engine/issues/39

Maybe we can just note which functions are left to add support for.

**Comment by saswatamcode** [comment]
Yup, we can close this one! I'll note down which functions are remaining in a separate issue 🙂
