### ISSUE TITLE
Unable to define logicalplan optimizer outside the package

### ISSUE THREAD

**Issue by yeya24** [thanos-community/promql-engine#238]
Hi, I am planning to define my own logical plan optimizer outside the package https://github.com/thanos-community/promql-engine/blob/main/logicalplan/plan.go#L39.

However, I am unable to do so because `github.com/thanos-community/promql-engine/internal/prometheus/parser` is an internal package.

We should probably still use the `promql.parser` package here to allow extension.

**Comment by fpetkovski** [comment]
Yeah this is not ideal, optimizers are a good extension point for the engine. Ideally we can use the prometheus parser, but if that's not possible, we might expose the internal parser as a public package.

**Comment by fpetkovski** [comment]
@yeya24 should we close this one?

**Comment by yeya24** [comment]
Yes, closing now.
