### ISSUE TITLE
Engine issue: different results with thanos and prometheus engines. group_left?

### ISSUE THREAD

**Issue by ahurtaud** [thanos-community/promql-engine#239]
Hello,

We have 2 similar thanos query (observee / observer) architectures. (query->queriers->sidecars):
One with the `prometheus` promql engine and one with the `thanos` promql engine and the following query gave different results with the thanos promql engines compared to thanos with prometheus engine and directly executed in prometheus also:

```
avg by (hrStorageDescr) (hrStorageUsed{nodename =~"xxxxx", } * on (instance, hrStorageIndex ) group_left(hrStorageDescr) (sum by (instance, hrStorageIndex, hrStorageDescr) (hrStorageDescr{nodename =~"xxxxx", hrStorageDescr!~".*Data.*"} ) ))
```

results with `thanos` engine (wrong one):
![Screenshot 2023-04-12 at 16 44 51](https://user-images.githubusercontent.com/25080995/231495023-9a8f2421-fb47-4636-8307-3bc520973d79.png)

results with `prometheus` engine (ok one):
![Screenshot 2023-04-12 at 16 47 38](https://user-images.githubusercontent.com/25080995/231495300-8f4f018c-28ae-4b90-afdd-c0ab4cdcc738.png)

results in prometheus ui directly:
![Screenshot 2023-04-12 at 16 48 32](https://user-images.githubusercontent.com/25080995/231496247-428798be-63a7-4161-9823-21a4d41a3f5f.png)

Sorry I had no time yet to try to reproduce with a "generic" exporter/query. I may try in the coming days.
I suspect group_left queries (maybe only with negative matchers?). Are those supported by the engine yet?

Thanks

**Comment by ahurtaud** [comment]
It is the top `avg by` aggregation that is "messing" the results. If I remove it in the `thanos` promql engine one. We can see it gets properly the 5 dimensions, but `avg by` wrongly aggregates them all:
![Screenshot 2023-04-12 at 16 53 03](https://user-images.githubusercontent.com/25080995/231497582-e514f7c4-bbd7-4422-9888-9792509d2596.png)

**Comment by fpetkovski** [comment]
I think they have the same engine version so updating won't help unfortunately. Is `avg` alone returning correct results?

**Comment by ahurtaud** [comment]
> I think they have the same engine version so updating won't help unfortunately. Is `avg` alone returning correct results?

on the right-hand side of the query `avg by` alone works:
![Screenshot 2023-04-12 at 17 13 29](https://user-images.githubusercontent.com/25080995/231506671-5b85fbfa-8b01-4c9d-a276-10a830fce60a.png)

the left-hand side metrics does not contain this label key (thats the purpose of group_left here), but if we avg by another dimension label contained by the left-side metrics, it seems ok:
![Screenshot 2023-04-12 at 17 27 50](https://user-images.githubusercontent.com/25080995/231506921-0478edf4-9f4e-489c-83e6-786ef3f18ede.png)


So I guess the issue would be when trying to "add" a label from an `*_info` metrics using `group_left` and then aggregating using this label. like explained in https://www.robustperception.io/why-info-style-metrics-have-a-value-of-1/

**Comment by fpetkovski** [comment]
Thanks for the detailed description, I'll try to reproduce the issue using these steps.
