### ISSUE TITLE
Investigate compliance testing

### ISSUE THREAD

**Issue by fpetkovski** [thanos-community/promql-engine#40]
We should investigate how to run compliance testing with something like:
* https://github.com/promlabs/promql-compliance-tester 
* https://github.com/prometheus/compliance

@yeya24 might have an idea of how this currently works for Thanos.

**Comment by yeya24** [comment]
@fpetkovski Since this repo is only a library, and we cannot use it with an actual implementation (like Thanos). Compliance test is more an E2E test. So does it make sense to use the Thanos compliance test now?

I think it is definitely good to have the compliance test in this repo, but some effort is needed.

**Comment by fpetkovski** [comment]
Understood, using the Thanos compliance test would definitely make sense. 
Maybe we can have an identical copy of that test, just with this engine enabled?

**Comment by yeya24** [comment]
I don't know what is the best way to go. But replying on Thanos is also affected by the Thanos implementation?
Besides, the test is an interactive test now, which means we need to run it locally. 

We want to run it through CI or some canary test, right?

**Comment by fpetkovski** [comment]
Good question. We can start by running it locally first. That should give us sufficient feedback on whether we have gaps in the implementation.

**Comment by GiedriusS** [comment]
Maybe fuzzing could be an option here? Basically, generate some data and continuously run random queries with both engines. Error out if the results are different (:

**Comment by fpetkovski** [comment]
Fuzzing does sound like a great idea too 👍

**Comment by yeya24** [comment]
I feel we don't need to integrate with the compliance test when we integrate the new fuzzer, right? It should cover the required cases. If some expressions are not supported, we can just support them in the fuzzer framework.

**Comment by fpetkovski** [comment]
I agree, local unit tests and fuzzing seems to be the way to go. Compliance testing looks too complicated to implement so I think we can close this for now.
