### ISSUE TITLE
Consider using multiple storage instances

### ISSUE THREAD

**Issue by fpetkovski** [thanos-community/promql-engine#67]
The current interface for creating an instant query takes a single storage instance:
```
NewInstantQuery(q storage.Queryable, opts *promql.QueryOpts, qs string, ts time.Time) (promql.Query, error)
```

We can consider allowing an array of storages so that the engine can fetch data in parallel. 

Since Thanos stores can shard data dybamically based on any labels, we can inject multiple storage instances, with each instance sharding data by ignoring replica labels. This will effectively make each storage independent and would allow the engine to fetch disjoint series in parallel.

The series request made by each storage instance would be something like
```
r := &storepb.SeriesRequest{
    MinTime: mint,
    MaxTime: max,
    Matchers: matchers,
    ...
    ShardInfo: storepb.ShardInfo {
        ShardIndex: i,
        TotalShards: n,
        By: false, // without
        Labels: replicaLabels
    },
}
```

**Comment by yeya24** [comment]
So this means we want to use a single Query Engine to handle multiple shards? This is different than the current Thanos engine as different query instance handle different shards, right?

**Comment by fpetkovski** [comment]
Yes, that would be the idea. It will allow us to make sharded requests in parallel, like we do for query sharding in thanos.

The alternative would be to allow the Thanos Storage to make multiple sharded requests and merge them together.

**Comment by fpetkovski** [comment]
I will close this in favour of the distributed execution mode.
