### ISSUE TITLE
increase + offset leads to funny results

### ISSUE THREAD

**Issue by GiedriusS** [thanos-community/promql-engine#90]
Something simple like:
```
increase(probe_success[1m] offset 24h)
```

returns `-0`. `increase(probe_success[1m])` returns `0` like expected. Original engine always returns `0`. Actually, sometimes the results are even something like `-2878.3789` which seems random :smile:

**Comment by yeya24** [comment]
😄 Seems a bug that I didn't catch. Can you please help reproduce it in a unit test with some example data?
