### ISSUE TITLE
disprepancy for `count(filter(...)) / count(..)` pattern

### ISSUE THREAD

**Issue by bwplotka** [thanos-community/promql-engine#96]
A version of engine:  (latest at the moment of submitting): 57585effffa199ae1d72f796fcc9fc086b6d1a81

Output: 

![image](https://user-images.githubusercontent.com/6950331/197931303-e1ce4e69-d075-4408-9d34-d5fcbc45fb58.png)

However, old engine gives this: 

![image](https://user-images.githubusercontent.com/6950331/197931199-003f3bcc-c7e9-4b20-a092-176329637b49.png)

**Comment by bwplotka** [comment]
With optimization disabled all works.

**Comment by fpetkovski** [comment]
@bwplotka are you still seeing the issue?

**Comment by fpetkovski** [comment]
AFAIK this should be resolved by now. Feel free to reopen :)
